name: Conformance Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  conformance:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"
          cache: gradle

      - name: Set up Node.js 24
        uses: actions/setup-node@v4
        with:
          node-version: "24"
          cache: npm
          cache-dependency-path: conformance-node/package-lock.json

      - name: Set gradlew permission
        run: chmod +x ./gradlew 

      - name: Compile conformance runner
        run: ./gradlew compileJava


      - name: Install conformance node dependencies
        run: npm ci
        working-directory: ./conformance-node

      - name: Run server conformance tests
        run: npm run test:server
        working-directory: ./conformance-node

      - name: Run quarkus conformance tests
        run: npm run test:quarkus
        working-directory: ./conformance-node

      - name: Run micronaut conformance tests
        run: npm run test:micronaut
        working-directory: ./conformance-node

      - name: Run spring-webflux conformance tests
        run: npm run test:springwebflux
        working-directory: ./conformance-node

      - name: Run spring-webmvc conformance tests
        run: npm run test:springwebmvc
        working-directory: ./conformance-node

      - name: Run ktor conformance tests
        run: npm run test:ktor
        working-directory: ./conformance-node
 
      - name: Run client conformance tests
        run: npm run test:client 
        working-directory: ./conformance-node

